Add support for cte materialization
constructive-io/pgsql-parser pull request #87
Opened 2022-09-13 09:58 UTC by tomquist

Currently, CTE materialization is dropped. This retains the materialization modifier for CTEs.

2022-09-13 17:08 UTC, pyramation requested changes
Hey this is awesome work! thanks so much :) 

My only thought is around breaking changes and since we modified the fixture, it's hard to ensure we didn't break something.

See my comment in the PR, but essentially if we can just duplicate the code you modified, so we have essentially 2 new statements added into the fixtures while keeping old syntax in-tact, I think we merge and publish!

2022-09-13 17:08 UTC, pyramation commented on __fixtures__/statements/select.sql
> +     ), top_regions AS NOT MATERIALIZED (
is there a way to keep the old fixture in place, and make another copy with the new change?

this helps ensure we don't have breaking changes for the previous syntax.

2022-09-13 17:08 UTC, pyramation commented on __fixtures__/statements/select.sql
>      select
same comment as above.

2022-09-14 14:17 UTC, merged

2022-09-14 15:09 UTC, pyramation commented
Thanks @tomquist for your contribution!

```
Successfully published:
 - pgsql-deparser@13.3.14
 - pgsql-parser@13.3.14
```

2022-09-15 07:33 UTC, tomquist commented
Awesome, thanks @pyramation!